<?php

namespace Database\Seeders;

use App\Models\Menu;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $menuItems = [
            [
                'category_id' => 1,
                'name' => 'Mie Goreng',
                'description' => 'Mie Goreng Indonesia',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 1,
                'name' => 'Mie Goreng Ayam',
                'description' => 'Mie Goreng Indonesia dengan topping ayam suwir',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 1,
                'name' => 'Mie Goreng Spesial',
                'description' => 'Mie Goreng Indonesia dengan toping ayam dan telur',
                'price' => 20000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 1,
                'name' => 'Mie Kuah',
                'description' => 'Mie Goreng Indonesia',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 1,
                'name' => 'Mie Kuah Ayam',
                'description' => 'Mie Kuah Indonesia dengan topping ayam suwir',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 1,
                'name' => 'Mie Kuah Spesial',
                'description' => 'Mie Kuah Indonesia dengan toping ayam dan telur',
                'price' => 20000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 2,
                'name' => 'Rice Bowl Ayam Teriaki',
                'description' => 'Rice Bowl lezat dengan Ayam Teriaki',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 2,
                'name' => 'Rice Bowl Ayam Lada Hitam',
                'description' => 'Rice Bowl lezat dengan Ayam lada Hitam',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 2,
                'name' => 'Rice Bowl Ayam BBQ',
                'description' => 'Rice Bowl lezat dengan Ayam BBQ',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 2,
                'name' => 'Rice Bowl Ayam Asam Manis',
                'description' => 'Rice Bowl lezat dengan Ayam Asam Manis',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 2,
                'name' => 'Rice Bowl Ayam Sambal Mata',
                'description' => 'Rice Bowl lezat dengan Ayam Sambal Mata',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 3,
                'name' => 'Nasi Ayam Geprek',
                'description' => 'Nasi Ayam Geprek dengan sambal',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 3,
                'name' => 'Nasi Bakwan Penyet',
                'description' => 'Nasi Bakwan Penyet dengan sambal',
                'price' => 20000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 3,
                'name' => 'Nasi 3T Penyet',
                'description' => 'Nasi Tahu, Tempe Penyet dengan sambal',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 3,
                'name' => 'Nasi 3T Telur Penyet',
                'description' => 'Nasi Tahu, Tempe, Telur Penyet dengan sambal',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 3,
                'name' => 'Nasi Putih',
                'description' => 'Nasi Putih saja',
                'price' => 4000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Kentang Goreng',
                'description' => 'Kentang Goreng Crispy',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Tahu Goreng Kriuk',
                'description' => 'Tahu Goreng Kriuk Crispy',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Pisang Goreng',
                'description' => 'Pisang Goreng',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Pisang Bakar',
                'description' => 'Bisang Bakar Manis',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Ayam POK',
                'description' => 'Ayam dadu goreng',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Tempe Mendoan',
                'description' => 'Tempe Mendoam',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Singkong Goreng',
                'description' => 'Singkong Goreng',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Sosis Bakar',
                'description' => 'Sosis Bakar',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Nugget',
                'description' => 'Nugget ayam goreng',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Roti Bakar Keju',
                'description' => 'Roti Bakar Keju',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Roti Bakar Cokelat',
                'description' => 'Roti Bakar Cokelat',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 4,
                'name' => 'Roti Bakar Strawberry',
                'description' => 'Roti Bakar Strawberry',
                'price' => 15000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Hot Vietnam Drip',
                'description' => 'Kopi hangat dengan metode Vietnam Drip',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Hot Vietnam Drip Susu',
                'description' => 'Kopi Susu hangat dengan metode Vietnam Drip',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Hot Kopi Onoeiki',
                'description' => 'Kopi ala Onoeiki',
                'price' => 5000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Hot Kopi Onoeiki Susu',
                'description' => 'Kopi susu hangat ala Onoeiki',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Ice Kopi Onoeiki Susu',
                'description' => 'Es Kopi Susu ala Onoeiki',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 5,
                'name' => 'Hot Kopi Tubruk Jahe',
                'description' => 'Kopi tubruk jahe hangat ala Onoeiki',
                'price' => 6000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Hot Chococlate',
                'description' => 'Cokelat hangat',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Ice Chocolate',
                'description' => 'Es cokelat',
                'price' => 12000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Hot Matcha',
                'description' => 'Matcha hangat ala Jepang',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Ice Matcha',
                'description' => 'Es matcha ala Jepang',
                'price' => 12000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Hot Red Velvet',
                'description' => 'Minuman Redvelvet hangat',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Ice Red Velvet',
                'description' => 'Minuman Redvelvet dingin',
                'price' => 12000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Hot Taro',
                'description' => 'Minuman Taro(talas) hangat',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Ice Taro',
                'description' => 'Minuman Taro(talas) dingin',
                'price' => 12000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Hot Bubblegum',
                'description' => 'Minuman rasa permenkaret hangat',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Ice Bubblegum',
                'description' => 'Minuman rasa perenkaret dingin',
                'price' => 12000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Nipis Hangat',
                'description' => 'Jeruk Nipis Hangat',
                'price' => 6000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Nipis Dingin',
                'description' => 'Jeruk Nipis Dingin',
                'price' => 7000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Manis Hangat',
                'description' => 'Jeruk Manis Hangat',
                'price' => 7000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Manis Dingin',
                'description' => 'Jeruk Manis Dingin',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Manis Dingin',
                'description' => 'Jeruk Manis Dingin',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Jeruk Manis Dingin',
                'description' => 'Jeruk Manis Dingin',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Es Soda Gembira',
                'description' => 'Es Soda dicampur dengan susu kental manis',
                'price' => 13000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Es Joshua',
                'description' => 'Es Extrajos dicampur dengan susu kental manis',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Es Mega Mendung',
                'description' => 'Es Cola dicampur dengan susu kental manis',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Air Mineral',
                'description' => 'Air Mineral',
                'price' => 5000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 6,
                'name' => 'Air Mineral Dingin',
                'description' => 'Air Mineral Dingin',
                'price' => 5000,'is_alcohol'=>false,
                'supplier_id' => 1,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Hot Jasmine Tea',
                'description' => 'Teh JAsmine hangat',
                'price' => 5000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Ice Jasmine Tea',
                'description' => 'Es Teh Jasmine',
                'price' => 6000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Hot Lemon Tea',
                'description' => 'Teh Lemon hangat',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Ice Lemon Tea',
                'description' => 'Es Teh Lemon',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Hot Butterfly Pea Tea',
                'description' => 'Teh Bunga telang hangat',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Ice Butterfly Pea Tea',
                'description' => 'Es Teh  bunga telang',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Hot Thai Tea',
                'description' => 'Teh Thailand hangat',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 7,
                'name' => 'Ice Thai Tea',
                'description' => 'Es Teh Thailand',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 8,
                'name' => 'Wedang Jahe',
                'description' => 'Wedang Jahe',
                'price' => 7000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 8,
                'name' => 'Wedang Uwuh',
                'description' => 'Wedang Uwuh',
                'price' => 8000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 8,
                'name' => 'Wedang Jahe Susu',
                'description' => 'Wedang Jahe Susu',
                'price' => 9000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 8,
                'name' => 'Wedang Uwuh Susu',
                'description' => 'Wedang Uwuh Susu',
                'price' => 10000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Lotus Blossom',
                'description' => 'Minuman Lotus Blossom',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Grenadine',
                'description' => 'Minuman Grenadine',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Rainbow Mojito',
                'description' => 'Minuman Rainbow Mojito',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Tropical Sunset',
                'description' => 'Minuman Tropical Sunset',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Strawberry Mojito',
                'description' => 'Minuman Strawberry Mojito',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Virgin Mojito',
                'description' => 'Minuman  Virgin Mojito',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 9,
                'name' => 'Blue Oceana',
                'description' => 'Minuman Blue Oceana',
                'price' => 18000,'is_alcohol'=>false,
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 4,
                'name' => 'Apidin',
                'description' => 'Bir Singaraja Apidin',
                'price' => 25000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/1.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 4,
                'name' => 'Abidin',
                'description' => 'Bir Singaraja Abidin',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 8,
                'photo' => 'images/2.jpeg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 3,
                'name' => 'Crystal',
                'description' => 'Bir Bintang Crystal',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.3,
                'photo' => 'images/3.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Konig Ludwig 500ml',
                'description' => 'Bir Konig Ludwig 500ml',
                'price' => 55000,'is_alcohol'=>true,
                'alcohol%' => 4.3,
                'photo' => 'images/4.jpeg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'kaltenberg',
                'description' => 'Bir Kaltenberg',
                'price' => 40000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/5.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 3,
                'name' => 'Bintang 620ml',
                'description' => 'Bir Bintang 620ml',
                'price' => 45000,'is_alcohol'=>true,
                'alcohol%' => 4.7,
                'photo' => 'images/6.jpeg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Draft 620ml',
                'description' => 'Draft Beer 620ml',
                'price' => 42000,'is_alcohol'=>true,
                'alcohol%' => 4.9,
                'photo' => 'images/7.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Guiness 330ml',
                'description' => 'Bir Guiness 330ml',
                'price' => 38000,'is_alcohol'=>true,
                'alcohol%' => 4.2,
                'photo' => 'images/8.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Heinekken 620ml',
                'description' => 'Bir Heinekken 620ml',
                'price' => 55000,'is_alcohol'=>true,
                'alcohol%' => 4.9,
                'photo' => 'images/9.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Mix Max Anggur Merah',
                'description' => 'Minuman vodka Mix Max Anggur Merah',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.5,
                'photo' => 'images/10.png',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Mix Max Exotic Blue',
                'description' => 'Minuman vodka Mix Max Exotic Blue',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/11.png',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Black Jack',
                'description' => 'Minuman alkohol Black Jack',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'is_combo'=>false,
                'photo' => 'images/12.jpg',
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Prost Alster 330ml',
                'description' => 'Bir Prost Alster 330ml',
                'price' => 27000,'is_alcohol'=>true,
                'alcohol%' => 2,
                'is_combo'=>false,
                'photo' => 'images/13.jpg',
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Prost Merah 620ml',
                'description' => 'Bir Prost Merah 620ml',
                'price' => 40000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/14.jpg',
                'is_combo'=>false,

            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Prost Biru 620ml',
                'description' => 'Bir Prost Biru 620ml',
                'price' => 43000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/15.jpg',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 3,
                'name' => 'Radler 330ml',
                'description' => 'Bir Bintang Radler 330ml',
                'price' => 27000,'is_alcohol'=>true,
                'alcohol%' => 0,
                'photo' => 'images/16.png',
                'is_combo'=>false,

            ], [
                'category_id' => 10,
                'supplier_id' => 4,
                'name' => 'Singaraja 620ml',
                'description' => 'Bir Singaraja 620ml',
                'price' => 35000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/17.png',
                'is_combo'=>false,

            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Smirnoff Green Apple',
                'description' => 'Minuman Beralkohol Smirnoff Green Apple',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.5,
                'photo' => 'images/19.jpg',
                'is_combo'=>false,

            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Smirnoff Pink Lemonade',
                'description' => 'Minuman Beralkohol Smirnoff Pink Lemonade',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.5,
                'photo' => 'images/22.png',
                'is_combo'=>false,

            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Smirnoff Raspberry Splash',
                'description' => 'Minuman Beralkohol Smirnoff Rasberry Splash',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 4.5,
                'photo' => 'images/20.png',
                'is_combo'=>false,
            ], [
                'category_id' => 10,
                'supplier_id' => 1,
                'name' => 'Smirnoff Vodka',
                'description' => 'Minuman beralkohol Smirnoff Vodka',
                'price' => 30000,'is_alcohol'=>true,
                'alcohol%' => 40,
                'photo' => 'images/21.png',
                'is_combo'=>false,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '4 Prost Alster',
                'description' => '4 Bir Prost Alster 330ml',
                'price' => 100000,'is_alcohol'=>true,
                'alcohol%' => 2,
                'photo' => 'images/23.jpg',
                'is_combo'=>true,
                'parent_id'=>87,
                'combo_quantity'=>4,
            ], [
                'category_id' => 11,
                'supplier_id' => 3,
                'name' => '4 Radler',
                'description' => '4 Bir Bintang Radler 330ml',
                'price' => 100000,'is_alcohol'=>true,
                'alcohol%' => 0,
                'photo' => 'images/24.png',
                'is_combo'=>true,
                'parent_id'=>90,
                'combo_quantity'=>4,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '4 Guiness',
                'description' => '4 Bir Guiness 330ml',
                'price' => 140000,'is_alcohol'=>true,
                'alcohol%' => 4.2,
                'photo' => 'images/25.jpg',
                'is_combo'=>true,
                'parent_id'=>82,
                'combo_quantity'=>4,
            ], [
                'category_id' => 11,
                'supplier_id' => 3,
                'name' => '3 Bintang',
                'description' => '3 Bir Bintang 620ml',
                'price' => 130000,'is_alcohol'=>true,
                'alcohol%' => 4.7,
                'photo' => 'images/27.jpeg',
                'is_combo'=>true,
                'parent_id'=>80,
                'combo_quantity'=>3,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '3 Draft',
                'description' => '3 Draft Beer 620ml',
                'price' => 115000,'is_alcohol'=>true,
                'alcohol%' => 4.9,
                'photo' => 'images/26.jpg',
                'is_combo'=>true,
                'parent_id'=>81,
                'combo_quantity'=>3,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '3 Heinekken',
                'description' => '3 Bir Heinekken 620ml',
                'price' => 155000,'is_alcohol'=>true,
                'alcohol%' => 4.9,
                'photo' => 'images/28.jpg',
                'is_combo'=>true,
                'parent_id'=>83,
                'combo_quantity'=>3,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '3 Prost Biru',
                'description' => '3 Bir Prost Biru 620ml',
                'price' => 120000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/29.jpg',
                'is_combo'=>true,
                'parent_id'=>89,
                'combo_quantity'=>3,
            ], [
                'category_id' => 11,
                'supplier_id' => 1,
                'name' => '3 Prost Merah',
                'description' => '3 Bir Prost Merah 620ml',
                'price' => 110000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/30.jpg',
                'is_combo'=>true,
                'parent_id'=>88,
                'combo_quantity'=>3,
            ], [
                'category_id' => 11,
                'supplier_id' => 4,
                'name' => '3 Singaraja',
                'description' => '3 Bir Singaraja 620ml',
                'price' => 100000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/31.png',
                'is_combo'=>true,
                'parent_id'=>91,
                'combo_quantity'=>3,
            ], [
                'category_id' => 12,
                'supplier_id' => 3,
                'name' => '4 Bintang',
                'description' => '4 Bir Bintang 620ml',
                'price' => 170000,'is_alcohol'=>true,
                'alcohol%' => 4.7,
                'photo' => 'images/32.jpeg',
                'is_combo'=>true,
                'parent_id'=>80,
                'combo_quantity'=>4,
            ], [
                'category_id' => 12,
                'supplier_id' => 1,
                'name' => '4 Prost Biru',
                'description' => '4 Bir Prost Biru 620ml',
                'price' => 160000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/33.jpg',
                'is_combo'=>true,
                'parent_id'=>89,
                'combo_quantity'=>4,
            ], [
                'category_id' => 12,
                'supplier_id' => 1,
                'name' => '4 Prost',
                'description' => '4 Bir Prost Merah 620ml',
                'price' => 150000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/34.jpg',
                'is_combo'=>true,
                'parent_id'=>88,
                'combo_quantity'=>4,
            ], [
                'category_id' => 12,
                'supplier_id' => 4,
                'name' => '4 Singaraja',
                'description' => '4 Bir Singaraja 620ml',
                'price' => 130000,'is_alcohol'=>true,
                'alcohol%' => 4.8,
                'photo' => 'images/35.png',
                'is_combo'=>true,
                'parent_id'=>91,
                'combo_quantity'=>4,
            ], [
                'category_id' => 12,
                'supplier_id' => 1,
                'name' => '4 Heinekken',
                'description' => '4 Bir Heinekken 620ml',
                'price' => 210000,
                'is_alcohol'=>true,
                'alcohol%' => 4.9,
                'photo' => 'images/36.jpg',
                'is_combo'=>true,
                'parent_id'=>83,
                'combo_quantity'=>4,
            ]
        ];
        foreach ($menuItems as $menuItem) {
            Menu::create($menuItem);
        }
    }
}
